language: cpp

branches:
  except:
    - master

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - doxygen
      - graphviz
      - perl
      - valgrind

fast_finish: true

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: linux
      compiler: clang

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]] ; then export CFLAGS="${CFLAGS} --coverage"; export CXXFLAGS="${CXXFLAGS} --coverage"; export LDFLAGS="${LDFLAGS} --coverage"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]] ; then pip install --user cpp-coveralls; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                     ; then brew update                                                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                     ; then brew install cmake    || brew outdated cmake    || brew upgrade cmake   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                     ; then brew install doxygen  || brew outdated doxygen  || brew upgrade doxygen ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                     ; then brew install graphviz || brew outdated graphviz || brew upgrade graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                     ; then brew install perl     || brew outdated perl     || brew upgrade perl    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                     ; then brew install valgrind || brew outdated valgrind || brew upgrade valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ]]   ; then brew install gcc      || brew outdated gcc      || brew upgrade gcc     ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ]]   ; then export CC="gcc-6"; export CXX="g++-6"                                   ; fi
  - mkdir -p build/test_install
  - pushd build
  - cmake ${CMAKE_OPTIONS} ..
  - if [[ -s doc/Doxyfile ]]                                ; then doxygen -u doc/Doxyfile                                                 ; fi

script:
  - make
  - make install DESTDIR="$(pwd)/test_install"
  - make memcheck

after_success:
  - popd
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC" == "gcc" ]] ; then coveralls -E '/usr/.*' -E '.*CMake.*' -E '.*/config.hpp' -E '.*test.*' --gcov-options '\-lp' > /dev/null; fi
