language: cpp

branches:
  except:
    - master

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - doxygen
      - graphviz
      - perl
      - valgrind

fast_finish: true

sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: linux
      compiler: clang

before_script:
  - if [[ "$CC" == "gcc" ]]                              ; then export CFLAGS="-Wall -Wextra -pedantic"; export CXXFLAGS="$CFLAGS"      ; fi
  - if [[ "$CC" == "clang" ]]                            ; then export CFLAGS="-Wall -Weverything -pedantic"; export CXXFLAGS="$CFLAGS" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$CC" == "gcc" ]]; then export CC="gcc-4.8"; export CXX="g++-4.8"                               ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                  ; then brew update                                                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                  ; then brew install cmake    || brew outdated cmake    || brew upgrade cmake   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                  ; then brew install doxygen  || brew outdated doxygen  || brew upgrade doxygen ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                  ; then brew install graphviz || brew outdated graphviz || brew upgrade graphviz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                  ; then brew install perl     || brew outdated perl     || brew upgrade perl    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]                  ; then brew install valgrind || brew outdated valgrind || brew upgrade valgrind; fi
  - mkdir -p build/test_install
  - pushd build
  - cmake ${CMAKE_OPTIONS} ..
  - if [[ -s doc/Doxyfile ]]                             ; then doxygen -u doc/Doxyfile                                                 ; fi

script:
  - make
  - make install DESTDIR="$(pwd)/test_install"
  - make memcheck
