language: cpp

branches:
  except:
    - master

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - doxygen
      - graphviz

matrix:
  fast_finish: true
  include:
  - compiler: gcc
    os: linux
  - compiler: clang
    os: linux
  - compiler: clang
    os: osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                              ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen graphviz perl       ; fi
  - mkdir -p build/test_install
  - pushd build
  - cmake ${CMAKE_OPTIONS} ..
  - if [[ -s doc/Doxyfile ]]           ; then doxygen -u doc/Doxyfile                  ; fi

script:
  - make
  - make install DESTDIR="$(pwd)/test_install"
  - ctest --output-on-failure
